import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Desk Table',
      slug: 'desk-table',
      category: 'Indoor Furniture',
      image: '/images/tables.jpg',
      price: 200,
      type: 'Table',
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
      description: 'Table in minimalistic design',
    },
    {
      name: 'Dining Table',
      slug: 'dining-tables',
      category: 'Indoor Furniture',
      image: '/images/whitetables.jpg',
      price: 170,
      type: 'Writing',
      rating: 4.2,
      numReviews: 15,
      countInStock: 10,
      description: 'Big dining tables with chairs together for living room',
    },
    {
      name: 'Bookcase',
      slug: 'bookcase',
      category: 'Indoor Furniture',
      image: '/images/case.jpg',
      price: 100,
      type: 'Wooden Bookcase',
      rating: 4.6,
      numReviews: 10,
      countInStock: 10,
      description: 'Wooden solid bookcase for home library',
    },
    {
      name: 'Chairs',
      slug: 'chairs',
      category: 'Outdoor Furniture',
      image: '/images/terrace.jpg',
      price: 180,
      type: 'Terrace Chairs',
      rating: 4.0,
      numReviews: 10,
      countInStock: 10,
      description: 'A pair of chairs for your terrace',
    },
    {
      name: 'Square Table',
      slug: 'square-table',
      category: 'Outdoor Furniture',
      image: '/images/SquareTable.jpg',
      price: 120,
      type: 'Dining Table_2',
      rating: 3.5,
      numReviews: 10,
      countInStock: 10,
      description: 'Square dining table for outdoor gatherings',
    },
    {
      name: 'Bench',
      slug: 'bench',
      category: 'Outdoor Furniture',
      image: '/images/Bench.jpg',
      price: 50,
      type: 'Wooden Bench',
      rating: 5.0,
      numReviews: 10,
      countInStock: 10,
      description: 'Wooden bench for outdoor',
    },
  ],
};
export default data;
